--- 
addons: 
  apt: 
    packages: 
      - aria2
build: 
  - "sh script.sh"
deploy: 
  api_key: $GH_KEY
  keep_history: true
  provider: releases
  file: hosts.deny
  skip_cleanup: true
  true: 
    branch: master
language: minimal
