--- 
addons: 
  apt: 
    packages: 
      - aria2
build: 
  - "sh script.sh"
deploy: 
  github_token: $GITHUB_TOKEN
  keep_history: true
  provider: pages
  skip_cleanup: true
  true: 
    branch: master
language: minimal
